---
name: "Build Image and upload to ghcr"
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        system: [x86_64-linux, aarch64-linux]
    runs-on: ubuntu-latest 
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          extra-platforms = aarch64-linux
          extra-sandbox-paths = /usr/bin
    - name: Build container image
      id: build_image
      run: |
        nix build .#packages.${{ matrix.system }}.iglu-cache-docker
        docker load < result

        version=$(docker images | grep iglu-cache-docker | head -n1 | awk '{print $2}')
        arch=$(docker images | grep iglu-cache-docker | head -n1 | awk '{print $2}' | cut -d- -f2)

        echo "version=$version" >> $GITHUB_OUTPUT
        echo "arch=$arch" >> $GITHUB_OUTPUT

        docker image tag iglu-cache-docker:$version iglu-cache-docker:latest-$arch 
    - name: Push To GHCR
      uses: redhat-actions/push-to-registry@v2.8
      with:
        image: iglu-cache-docker  
        tags: ${{ steps.build_image.outputs.version }} latest-${{ steps.build_image.outputs.arch }}
        registry: ghcr.io/${{ github.repository_owner }}
        username: ${{ github.actor }} 
        password: ${{ secrets.GITHUB_TOKEN }}
        extra-args: |
          --disable-content-trust

