---
name: "Combine images to multiarch"
on:
  workflow_run:
    workflows: [Build Image and upload to ghcr]
    types:
      - completed
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Build multiarch image
      id: build_image
      run: |
        version=$(cat package.json | grep version | awk '{print $2}' | cut -d'"' -f 2)
        echo "version=$version" >> $GITHUB_OUTPUT
        for tag in $version latest; do
          docker pull ghcr.io/iglu-api/iglu-cache-docker:$tag-arm64
          docker pull ghcr.io/iglu-api/iglu-cache-docker:$tag-amd64
          docker manifest create iglu-api/iglu-cache-docker:$tag \
            iglu-api/iglu-cache-docker:$tag-amd64 \
            iglu-api/iglu-cache-docker:$tag-arm64
          docker manifest annotate iglu-api/iglu-cache-docker:$tag \
            iglu-api/iglu-cache-docker:$tag-arm64 --arch arm64
          docker manifest annotate iglu-api/iglu-cache-docker \
            iglu-api/iglu-cache-docker:$tag-amd64 --arch amd64
        done

    - name: Push To GHCR
      uses: redhat-actions/push-to-registry@v2.8
      with:
        image: iglu-cache-docker  
        tags: ${{ steps.build_image.outputs.version }}
        registry: ghcr.io/${{ github.repository_owner }}
        username: ${{ github.actor }} 
        password: ${{ secrets.GITHUB_TOKEN }}
        extra-args: |
          --disable-content-trust
