---
name: "Build Image and upload to ghcr"
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v4
    - uses: gacts/install-podman@v1
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Build container image
      id: build_image
      run: |
        nix build .#iglu-cache-docker
        podman load < result
        echo version=$(docker images | grep iglu-cache-docker | awk '{print $2}') >> "$GITHUB_OUTPUT"
        podman image tag iglu-cache-docker:$(podman images | grep iglu-cache-docker | head -n1 | awk '{print $2}') iglu-cache-docker:latest 
    - name: Push To GHCR
      uses: redhat-actions/push-to-registry@v2.8
      with:
        image: iglu-cache-docker  
        tags: ${{ steps.build_image.outputs.version }} latest
        registry: ghcr/${{ github.repository_owner }}
        username: ${{ github.actor }} 
        password: ${{ github.token }}
        extra-args: |
          --disable-content-trust

