---
name: "Build Image and upload to ghcr"
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest 
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          extra-platforms = aarch64-linux
          extra-sandbox-paths = /usr/bin
    - name: Build container image
      id: build_image
      run: |
        for system in x86_64-linux aarch64-linux; do
          nix build .#packages.$system.iglu-cache-docker
          docker load < result

          version=$(docker images | grep iglu-cache-docker | head -n1 | awk '{print $2}' | cut -d- -f1)

          echo "version=$version" >> $GITHUB_OUTPUT
        done
    - name: Push To GHCR
      uses: redhat-actions/push-to-registry@v2.8
      with:
        image: iglu-cache-docker  
        tags: ${{ steps.build_image.outputs.version }}-arm64 ${{ steps.build_image.outputs.version }}-amd64
        registry: ghcr.io/${{ github.repository_owner }}
        username: ${{ github.actor }} 
        password: ${{ secrets.GITHUB_TOKEN }}
        extra-args: |
          --disable-content-trust
    - name: Build Multiarch
      run: |
        docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
        for tag in latest $version; do
          docker manifest create ghcr.io/iglu-api/iglu-cache-docker:$tag \
            ghrc.io/iglu-api/iglu-cache-docker:$version-amd64 \
            ghrc.io/iglu-api/iglu-cache-docker:$version-arm64
          docker manifest annotate iglu-api/iglu-cache-docker:$tag \
            ghrc.io/iglu-api/iglu-cache-docker:$version-arm64 --arch arm64
          docker manifest annotate iglu-api/iglu-cache-docker:$tag \
            ghrc.io/iglu-api/iglu-cache-docker:$version-amd64 --arch amd64
          docker manifest push ghcr.io/iglu-api/iglu-cache-docker:$tag
        done
      env:
        version: ${{ steps.build_image.outputs.version }}

