---
name: "Check build"
permissions:
  contents: read
on:
  pull_request:

jobs:
  check_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64-linux, aarch64-linux]
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: "Build docker"
        run: nix build .#packages.${{ matrix.arch }}.iglu-cache-docker

