---
name: "Check build and nix formatting"
permissions:
  contents: read
on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: "Check nix stuff"
        run: nix develop --command flakecheck
      - name: "Build docker"
        run: nix build .#iglu-cache-docker

