---
name: "Check build"
permissions:
  contents: read
on:
  pull_request:

jobs:
  check_build:
    strategy:
      matrix:
        runner: [ubuntu-latest, ubuntu-latest-arm]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: "Build docker"
        run: nix build .#iglu-cache-docker

